toolbar:
  - styleselect | bold italic underline aligncenter alignleft alignright alignjustify blockquote code strikethrough fontname fontsize | undo redo | image | link
plugins:
  - image
  - link
  - wordcount